language: node_js
node_js: lts/*
matrix:
  include:
    - os: osx
      osx_image: xcode11
      addons:
        chrome: stable
        firefox: latest
    - os: windows
branches:
  only:
    - master
script:
  - npm run test:coverage
  - codecov
